project:
  type: website
  output-dir: _site

website:
  title: "Introduction to Coding and Data Analysis"
  description: "A comprehensive course covering NumPy, Matplotlib, and advanced Python concepts"


  navbar:
    title: "Intro to Coding & Data Analysis"


    left:
      - href: index.qmd
        text: Home
      - text: "Lessons"
        menu:
          - text: "01 - Introduction to Data Types"
            href: 01/week_01_home.qmd
          - text: "07 - Introduction to NumPy"
            href: 07/lecture_intro_numpy.qmd
          - text: "08 - Working with NumPy"
            href: 08/lecture_working_with_numpy.qmd
          - text: "09 - Introduction to Matplotlib"
            href: 09/lecture_intro_matplotlib.qmd
          - text: "10 - Multidimensional Arrays"
            href: 10/lecture_multidimensionalArrays.qmd
          - text: "11 - Beyond the Notebook"
            href: 11/lecture_beyond_the_notebook.qmd
      - text: "Exercises"
        menu:
          - text: "Week 01 - Data Types"
            menu:
              - text: "Beginner"
                href: 01/week_01_intro_to_data_types_beginner.qmd
              - text: "Intermediate"
                href: 01/week_01_intro_to_data_types_intermediate.qmd
              - text: "Advanced"
                href: 01/week_01_intro_to_data_types_advanced.qmd
          - text: "Week 07 - NumPy"
            menu:
              - text: "Exercises"
                href: 07/exercises_numpy.qmd
          - text: "Week 08 - NumPy Working"
            menu:
              - text: "Exercises"
                href: 08/exercises_lecture_working_with_numpy.qmd
          - text: "Week 09 - Plotting"
            menu:
              - text: "Exercises"
                href: 09/exercises_plotting_data_from_file.qmd
          - text: "Week 10 - Part 1 & 2"
            menu:
              - text: "Part 1"
                href: 10/exercises_part1.qmd
              - text: "Part 2"
                href: 10/exercises_part2.qmd
          - text: "Week 11 - Riddles"
            menu:
              - text: "NumPy"
                href: 11/exercises_numpy_riddles.qmd
              - text: "Python"
                href: 11/exercises_python_riddles.qmd

      - text: "Solutions"
        menu:
          - text: "07 - NumPy Solutions"
            href: 07/exercises_numpy_solutions.qmd
          - text: "08 - NumPy Working Solutions"
            href: 08/exercises_lecture_working_with_numpy_solutions.qmd
          - text: "09 - Plotting Solutions"
            href: 09/exercises_plotting_data_from_file_solutions.qmd
          - text: "10 - Part 1 Solutions"
            href: 10/exercises_part1_solutions.qmd
          - text: "10 - Part 2 Solutions"
            href: 10/exercises_part2_solutions.qmd
          - text: "11 - NumPy Riddles Solutions"
            href: 11/exercises_numpy_riddles_solutions.qmd
          - text: "11 - Python Riddles Solutions"
            href: 11/exercises_python_riddles_solutions.qmd

      - text: "Formative tests"
        menu:
          - text: "Variables, lists, dictionaries and branches"
            href: formative/basic_structures.qmd

      # - text: "Examples"
      #   menu:
      #     - text: "09 - Matplotlib Fun Decorations"
      #       href: 09/fun_matplotlib_decoration.qmd
      #     - text: "11 - Example Notebook"
      #       href: 11/example.qmd
    
    # right:
    #   - icon: github
    #     href: https://github.com/
    
  sidebar:
    logo: figs/banner.png
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "Course Overview"
        contents:
          - index.qmd

      - section: "01 Introduction to Data Types"
        contents:
          - 01/week_01_home.qmd
          - 01/week_01_intro_to_data_types_beginner.qmd
          - 01/week_01_intro_to_data_types_intermediate.qmd
          - 01/week_01_intro_to_data_types_advanced.qmd
      
      - section: "07 Introduction to NumPy"
        contents:
          - 07/lecture_intro_numpy.qmd
          - 07/exercises_numpy.qmd
          - text: "Solutions"
            href: 07/exercises_numpy_solutions.qmd
      
      - section: "08 Working with NumPy"
        contents:
          - 08/lecture_working_with_numpy.qmd
          - 08/exercises_lecture_working_with_numpy.qmd
          - text: "Solutions"
            href: 08/exercises_lecture_working_with_numpy_solutions.qmd
      
      - section: "09 Introduction to Matplotlib"
        contents:
          - 09/lecture_intro_matplotlib.qmd
          - 09/exercises_plotting_data_from_file.qmd
          - text: "Solutions"
            href: 09/exercises_plotting_data_from_file_solutions.qmd
          - 09/fun_matplotlib_decoration.qmd
      
      - section: "10 Multidimensional Arrays"
        contents:
          - 10/lecture_multidimensionalArrays.qmd
          - 10/exercises_part1.qmd
          - text: "Solutions - Part 1"
            href: 10/exercises_part1_solutions.qmd
          - 10/exercises_part2.qmd
          - text: "Solutions - Part 2"
            href: 10/exercises_part2_solutions.qmd
          - 10/hint1_mask.qmd
          - 10/hint2_apply_mask.qmd
      
      - section: "11 Beyond the Notebook"
        contents:
          - 11/lecture_beyond_the_notebook.qmd
          - 11/exercises_numpy_riddles.qmd
          - text: "Solutions - NumPy Riddles"
            href: 11/exercises_numpy_riddles_solutions.qmd
          - 11/exercises_python_riddles.qmd
          - text: "Solutions - Python Riddles"
            href: 11/exercises_python_riddles_solutions.qmd
          - 11/example.qmd

  page-footer:
    left: "© 2024 Introduction to Coding and Data Analysis"
    # right: "Built with [Quarto](https://quarto.org/)"

format:
  live-html:
    include-in-header:
      text: |
        <meta name="robots" content="noindex, nofollow">
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    number-sections: False
    link-external-newwindow: true
    grid:
      sidebar-width: 350px
execute:
  freeze: auto
  cache: true
  error: true

